### ISSUE TITLE
[probably bug] feature detection probably does not work

### ISSUE THREAD

**Issue by bigopon** [WebReflection/custom-elements-builtin#3]
A screen shot for iOS 14, Safari 
![image](https://user-images.githubusercontent.com/9994529/98190262-c199ab00-1f6a-11eb-8bc3-2d8ebc6c5637.png)

It's working fine for iOS13, Safari though.

An example you can test is this page https://www.open.edu.au/subjects/macquarie-university-doing-social-survey-research-maq-socx830 (scroll down to the save button):

iOS13
![image](https://user-images.githubusercontent.com/9994529/98190883-1e499580-1f6c-11eb-9b29-5d30d00550d5.png)

iOS14
![image](https://user-images.githubusercontent.com/9994529/98190934-391c0a00-1f6c-11eb-80cd-1751e7e138b9.png)

---

I assumed that the feature detection based on `.define` call isn't reliable, I think it used to be on/off with different combos of iOS + Safari versions

**Comment by WebReflection** [comment]
The feature detection changed and the polyfill you should use is this one https://github.com/ungap/custom-elements#readme which includes the *right* feature detection.

Can you try that instead? This module is not supposed to be used standalone *unless* you target Safari/WebKit **only**

**Comment by bigopon** [comment]
Right, thanks for the hint, tried this and it worked fine. I was conditionally polyfilling based on the availability of `customElements`, but this is a lot cleaner.

**Comment by WebReflection** [comment]
> I was conditionally polyfilling based on the availability of `customElements`

You were doing the right thing, and it also was suggested in the README (which I've changed), but the current polyfill for all browsers work better, is smaller, doesn't require people to remember or know which feature detection is needed for what, and on top of that, normalizes `whenDefined` [to its latest standard](https://webreflection.medium.com/a-journey-to-web-standards-contribution-8027bb874908).

I know it's annoying to serve 2K to all browsers, but even most recent one, needs the poly to have an up-to-date `whenDefined`, so I also hope this is acceptable.

**Comment by bigopon** [comment]
Thanks for the hints, and the suggestions. I don't think it's that annoying to serve extra 2KB at all. In fact, it makes me feel good having that 2KB for extend built-in capabilities, and show some folks the beauty of extended built-in CE.
